version: "3.1"

services:

  elasticsearch:
    image: elasticsearch:7.1.1
    volumes:
      - ./data:/usr/share/elasticsearch/data:rw
      - ./logs:/usr/share/elasticsearch/logs:rw
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always

  elasticsearch-head:
    image: mobz/elasticsearch-head:5
    ports:
      - 9100:9100
    depends_on:
      - elasticsearch
    restart: always
